// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pipeline/output.proto

package pipeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoredCertificateLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject    string  `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	LogUrl     string  `protobuf:"bytes,2,opt,name=log_url,json=logUrl,proto3" json:"log_url,omitempty"`
	Index      int64   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	TotalScore float32 `protobuf:"fixed32,4,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	AlgScore   float32 `protobuf:"fixed32,5,opt,name=alg_score,json=algScore,proto3" json:"alg_score,omitempty"`
	MlScore    float32 `protobuf:"fixed32,6,opt,name=ml_score,json=mlScore,proto3" json:"ml_score,omitempty"`
}

func (x *ScoredCertificateLog) Reset() {
	*x = ScoredCertificateLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipeline_output_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoredCertificateLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredCertificateLog) ProtoMessage() {}

func (x *ScoredCertificateLog) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_output_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredCertificateLog.ProtoReflect.Descriptor instead.
func (*ScoredCertificateLog) Descriptor() ([]byte, []int) {
	return file_pipeline_output_proto_rawDescGZIP(), []int{0}
}

func (x *ScoredCertificateLog) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ScoredCertificateLog) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

func (x *ScoredCertificateLog) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ScoredCertificateLog) GetTotalScore() float32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *ScoredCertificateLog) GetAlgScore() float32 {
	if x != nil {
		return x.AlgScore
	}
	return 0
}

func (x *ScoredCertificateLog) GetMlScore() float32 {
	if x != nil {
		return x.MlScore
	}
	return 0
}

var File_pipeline_output_proto protoreflect.FileDescriptor

var file_pipeline_output_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22,
	0xb8, 0x01, 0x0a, 0x14, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x64, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6c, 0x67, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x61, 0x6c, 0x67, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x6c, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x07, 0x6d, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x7f, 0x0a, 0x0a, 0x63, 0x6f,
	0x6d, 0x2e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x0b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x33, 0x64, 0x61, 0x73, 0x2f, 0x72, 0x69, 0x76, 0x65, 0x72, 0x66,
	0x69, 0x73, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0xa2, 0x02, 0x03, 0x4f, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0xca, 0x02, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0xe2, 0x02, 0x12,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pipeline_output_proto_rawDescOnce sync.Once
	file_pipeline_output_proto_rawDescData = file_pipeline_output_proto_rawDesc
)

func file_pipeline_output_proto_rawDescGZIP() []byte {
	file_pipeline_output_proto_rawDescOnce.Do(func() {
		file_pipeline_output_proto_rawDescData = protoimpl.X.CompressGZIP(file_pipeline_output_proto_rawDescData)
	})
	return file_pipeline_output_proto_rawDescData
}

var file_pipeline_output_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pipeline_output_proto_goTypes = []interface{}{
	(*ScoredCertificateLog)(nil), // 0: output.ScoredCertificateLog
}
var file_pipeline_output_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pipeline_output_proto_init() }
func file_pipeline_output_proto_init() {
	if File_pipeline_output_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pipeline_output_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoredCertificateLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pipeline_output_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pipeline_output_proto_goTypes,
		DependencyIndexes: file_pipeline_output_proto_depIdxs,
		MessageInfos:      file_pipeline_output_proto_msgTypes,
	}.Build()
	File_pipeline_output_proto = out.File
	file_pipeline_output_proto_rawDesc = nil
	file_pipeline_output_proto_goTypes = nil
	file_pipeline_output_proto_depIdxs = nil
}
