# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline/output.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pipeline/output.proto\x12\x06output\"\xb8\x01\n\x14ScoredCertificateLog\x12\x18\n\x07subject\x18\x01 \x01(\tR\x07subject\x12\x17\n\x07log_url\x18\x02 \x01(\tR\x06logUrl\x12\x14\n\x05index\x18\x03 \x01(\x03R\x05index\x12\x1f\n\x0btotal_score\x18\x04 \x01(\x02R\ntotalScore\x12\x1b\n\talg_score\x18\x05 \x01(\x02R\x08\x61lgScore\x12\x19\n\x08ml_score\x18\x06 \x01(\x02R\x07mlScoreB\x7f\n\ncom.outputB\x0bOutputProtoP\x01Z,github.com/K3das/riverfish/proto/go/pipeline\xa2\x02\x03OXX\xaa\x02\x06Output\xca\x02\x06Output\xe2\x02\x12Output\\GPBMetadata\xea\x02\x06Outputb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline.output_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\ncom.outputB\013OutputProtoP\001Z,github.com/K3das/riverfish/proto/go/pipeline\242\002\003OXX\252\002\006Output\312\002\006Output\342\002\022Output\\GPBMetadata\352\002\006Output'
  _SCOREDCERTIFICATELOG._serialized_start=34
  _SCOREDCERTIFICATELOG._serialized_end=218
# @@protoc_insertion_point(module_scope)
