# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline/ingest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pipeline/ingest.proto\x12\x06injest\"Y\n\x0e\x43\x65rtificateLog\x12\x18\n\x07subject\x18\x01 \x01(\tR\x07subject\x12\x14\n\x05index\x18\x02 \x01(\x03R\x05index\x12\x17\n\x07log_url\x18\x03 \x01(\tR\x06logUrlB\x7f\n\ncom.injestB\x0bIngestProtoP\x01Z,github.com/K3das/riverfish/proto/go/pipeline\xa2\x02\x03IXX\xaa\x02\x06Injest\xca\x02\x06Injest\xe2\x02\x12Injest\\GPBMetadata\xea\x02\x06Injestb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline.ingest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\ncom.injestB\013IngestProtoP\001Z,github.com/K3das/riverfish/proto/go/pipeline\242\002\003IXX\252\002\006Injest\312\002\006Injest\342\002\022Injest\\GPBMetadata\352\002\006Injest'
  _CERTIFICATELOG._serialized_start=33
  _CERTIFICATELOG._serialized_end=122
# @@protoc_insertion_point(module_scope)
